export { Landing } from "./landing/Landing";
export { Login } from "./login/login";
export { SignUp } from "./signup/SignUp";
export { NotesHome } from "./notes-home/NotesHome";
export { Profile } from "./Profile/Profile";
export { Archive } from "./archive/Archive";
export { Trash } from "./trash/Trash";
export { SingleLabel } from "./singleLabel/SingleLabel";
export { Error404 } from "./error404/Error404";
